version: "3"

services:
  app-dev:
    build: app
    container_name: django-dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/src/
    command:
      "python manage.py runserver 0.0.0.0:8000"
